### ISSUE TITLE
Update POT

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#149]
I have the first finished translation and realized that I missed a few phrases in the gettext calls. I need to add in the tab names from the quiz settings page and the columns on the quizzes page. Also, some text of the help page.

**Comment by OC2PS** [comment]
Would be really good if you put this on GlotPress. Lots of other projects use it and it is an awesome way to get translations.

**Comment by fpcorso** [comment]
Updated POT and added 5 translations for this update in #158
