### ISSUE TITLE
Smarten Punctuation

### ISSUE THREAD

**Issue by jmferrell** [fpcorso/quiz_master_next#163]
Add an option (or maybe default?) to always use "curly" quotes and apostrophes in questions and multiple choice responses

**Comment by fpcorso** [comment]
Hey Jeff! Can you elaborate a little more on this? What are you using the curly quotes for?

**Comment by jmferrell** [comment]
Example: http://ferrellweb.com/q3exam/ —first and second question, for instance. If entered normally, apostrophes come out straight. I'm entering &rsquo; (or shift-option-] on a Mac) to make them curly. Maybe an issue with my WordPress install?

**Comment by fpcorso** [comment]
Ah. I understand now. That is the default behavior for most things.  If I type a quote here ' it will turn out straight too.

**Comment by fpcorso** [comment]
I don't know about converting them to curly in the plugin because not everyone would want them curly.

**Comment by jmferrell** [comment]
Indeed. Maybe an option-toggle somewhere, or maybe not worth pursuing at all. I've just been typing a *ton* of shift-option-]'s! 

Come to think of it, I've used the (now defunct?) wp-Typography plugin on sites in the past to handle that kind of thing. I wonder if (a) it's still functional, and (b) if it would catch QMN output before it hit the page? I could give it a try...

Zap this issue, if you'd like; popped into my head, so I thought I'd float it. It's not too difficult to custom-punctuate on the fly.

**Comment by jmferrell** [comment]
For the record, the wp-typography plugin catches and replaces them. No worries!

**Comment by fpcorso** [comment]
Ah, that is good news. I will look into that plugin and perhaps incorporate an option down the road perhaps.
