### ISSUE TITLE
Copy Questions Between Quizzes

### ISSUE THREAD

**Issue by jmferrell** [fpcorso/quiz_master_next#166]
The ability to copy a question from one quiz to another (for re-use, etc.). Could be a separate "Copy to quiz..." item in the row-actions, or integrated with the "Duplicate" dialog box somehow.

**Comment by fpcorso** [comment]
Hmmm...interesting. This is similar to what the user wanted the master bank for in issue #39 The user wanted all questions to be in a large bank of questions that could be re-used in later quizzes.

**Comment by fpcorso** [comment]
I guess more people wanted this ability than I thought.

**Comment by jmferrell** [comment]
Oops. +1, then!

**Comment by jmferrell** [comment]
...Although not *exactly* the same; a question bank sounds like a massive undertaking, at least as far as UI goes.

**Comment by fpcorso** [comment]
It could be. Perhaps we could start with a "copy to quiz" action item first and then eventually roll out the question back.

**Comment by adarshmadrecha** [comment]
Yes, having a common question bank and then assigning quiz to each questions will be helpfull in managing large database of questions.

**Comment by fpcorso** [comment]
It's been quite a while @jmferrell but this request is finally making it into an update. Just finished this feature and merged into the 'dev' branch. Will make it to the public in 4.7.0!
