### ISSUE TITLE
Searchable Results

### ISSUE THREAD

**Issue by jmferrell** [fpcorso/quiz_master_next#167]
Add the ability to search/filter results based on Name, Business, Email, etc. (could that leverage Wordpress' Search Posts functionality, or does that need to be developed separately?)

Use case: If I use QMN to give a quiz to 80+ students, and need to verify a score, I have to manually flip through pages of results.

**Comment by fpcorso** [comment]
Ah, that makes sense. Unfortunately, I cannot utilize the Search Posts system due to how the results are currently structured. I will see what I can do for you.

**Comment by jmferrell** [comment]
No hurry or anything—just a thought as I was working with it. :)
