### ISSUE TITLE
Option to have the next page button grayed out when a quiz is in progress

### ISSUE THREAD

**Issue by gamekid88** [fpcorso/quiz_master_next#187]
Users want to be able to grey the "next page" button out when a quiz has multiple pages. They want to have the option to prevent continuing the quiz until the current page's questions have been answered.

**Comment by fpcorso** [comment]
I think that this is now irrelevant due to #198 which prevents users from going forward if the required questions have not been answered.

**Comment by fpcorso** [comment]
@gamekid88
