### ISSUE TITLE
Email not working for user

### ISSUE THREAD

**Issue by SangameshPH** [fpcorso/quiz_master_next#195]
Hello,

Thanks for wonderful plugin.
I am facing some problem with email notification. Both user and admin never gets a mail when someone takes the test. It never worked for me. I tried everything. Could you please help me to set this up?
Thanks,
-/Sammi

**Comment by fpcorso** [comment]
Hey Sammi! If you can read over the guidelines for bug reports here: https://github.com/fpcorso/quiz_master_next/blob/master/CONTRIBUTING.md Try following the steps in the Debug section and let me know how that works. Also, can you provide me the information listed in the "For bug reports" part of the Creating Issues section?

**Comment by robwoodgate** [comment]
This could very likely be linked to the redirect results issue... 
https://github.com/fpcorso/quiz_master_next/issues/201

**Comment by fpcorso** [comment]
Possibly, I have an long open bug #30 that has affected a few users over the last few months before the redirect was introduced that I haven't been able to resolve yet.

**Comment by fpcorso** [comment]
Hey Sammi,

When I re-wrote the core quiz functions, did that resolve your email issue?

**Comment by SangameshPH** [comment]
Hey Frank, 
Let me check it and come back to you.

Warm regards,
Sangamesh
