### ISSUE TITLE
Long quiz URL mungs page layout

### ISSUE THREAD

**Issue by robwoodgate** [fpcorso/quiz_master_next#202]
If a Quiz has a long url, it mangles the layout of the main admin quizzes page by flowing the quiz selector box into the right hand sidebar.

**Comment by fpcorso** [comment]
@robwoodgate Greetings! Is this the main quizzes page where you create quizzes? Can you provide a sample screenshot?

**Comment by robwoodgate** [comment]
Yes, it's the main quiz page: /wp-admin/admin.php?page=quiz-master-next/mlw_quizmaster2.php

![screen shot 2015-04-23 at 15 26 14](https://cloud.githubusercontent.com/assets/12084212/7299331/2c6689d2-e9cd-11e4-921a-0729065a4e48.png)

Cheers
Rob

**Comment by fpcorso** [comment]
Ah, yeah that looks like a problem indeed. I'll get a fix in the next update for you.

**Comment by fpcorso** [comment]
Fixed in recent commit.
