### ISSUE TITLE
FPDF WriteHTML Path Not Being Created Correctly On Windows

### ISSUE THREAD

**Issue by aniketagarwal** [fpcorso/quiz_master_next#204]
when i wish to see the certificate in my results page using template variable the download certificate gives me the following error. And email is also not working.

Warning: include(C: mpp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php//fpdf/WriteHTML.php): failed to open stream: Invalid argument in C:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\certificates\mlw_qmn_quiz2015042420201069.php on line 2

Warning: include(): Failed opening 'C: mpp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php//fpdf/WriteHTML.php' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\certificates\mlw_qmn_quiz2015042420201069.php on line 2

Fatal error: Class 'PDF_HTML' not found in C:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\certificates\mlw_qmn_quiz2015042420201069.php on line 3

**Comment by fpcorso** [comment]
Greetings @aniketagarwal  I am sorry to hear that you are experiencing this issue. It looks like the problems is how the plugin is creating the url to one of the certificate functions on Windows. I'll get this fixed in the next update for you.

Thanks for reporting this!

**Comment by aniketagarwal** [comment]
Yeah the certificate is working fine when i published my site.

**Comment by fpcorso** [comment]
Fixed the slash issue in the referenced commit.
