### ISSUE TITLE
Email from field not working

### ISSUE THREAD

**Issue by ClientLeads** [fpcorso/quiz_master_next#212]
I am creating the email to be sent after my quiz is completed. I have put in the name in the "email from" area and the emails continue to come from:   <> instead of the name I put in. thanks.

**Comment by fpcorso** [comment]
Hey @ClientLeads thanks for choosing to use this plugin!

On your email tab, do you have content in the "What emails should we send the admin email to? Separate emails with a comma." option.? Is it a singular email address or muliples? If it is multiples, can you remove the rest and leave a single email to see if that resolves the issue?

Also, to better debug this, can you follow the guidelines for creating issues (https://github.com/fpcorso/quiz_master_next/blob/master/CONTRIBUTING.md#creating-issues) and respond back the results from the guidelines?
