### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by PhilSil** [fpcorso/quiz_master_next#219]
Hi

we really like this plugin. But we would like to have an option to make answers case sensitive. Is such a feature planed for future releases?

Regards
PhilSil

**Comment by fpcorso** [comment]
Greetings! Thank you for choosing to use this plugin. Are you referring to the open answer types? We had specifically designed it to be not case sensitive to assist in users answering. Can you provide an example of when case sensitive is required?

**Comment by PhilSil** [comment]
We want to create a webpage offering dictation for pupils. We upload Mp3s to our website and our website-visitors can listen to the sound files. We want to offer them the opportunity to write down what they heared (into the text box). We want to give them feedback on their writing skills. In that case we need case sensivity. It would be really great if there was this option. If you tell me where I can change that option within the code I can also try to do it myself.

**Comment by fpcorso** [comment]
Hmmm...interesting. I will keep this in mind in the future updates for. If you want to try to create a workaround in the code, all the questions types are stored in the question type file here: https://github.com/fpcorso/quiz_master_next/blob/master/php/qmn_question_types.php#L205  I highlighted the line that begins the small open answer type.

**Comment by PhilSil** [comment]
Thank you! Now I adapted it to my needs, no big deal :).
