### ISSUE TITLE
Sorting of questions by Categories

### ISSUE THREAD

**Issue by gamekid88** [fpcorso/quiz_master_next#223]
Admins want to be able to sort questions by category when a user takes a quiz. For example, if an admin creates a series of questions about oceans and then another series of questions about boats in the same quiz then they want to have all the ocean questions sorted together on the quiz and the same for all boat questions.

**Comment by fpcorso** [comment]
Another user has requested the ability to create category sections.

**Comment by fpcorso** [comment]
With the system proposed in #568, the system will no longer create pages as they ability is given to the user. So, the user will now group the questions in the category together on their own so this issue will be irrelevant.
