### ISSUE TITLE
Redirect shows only empty page.

### ISSUE THREAD

**Issue by PhilSil** [fpcorso/quiz_master_next#226]
Redirect does not work. It only shows an empty page. Results do not get stored, too. We would really need that function working correctly.

Thanks
PhilSil

**Comment by fpcorso** [comment]
Greetings PhilSil. I am sorry to hear you are encountering this issue. This has already been reported in #201

**Comment by fpcorso** [comment]
Ah, only the results not being stored has been reported.

When you say that the redirect only shows an empty page, is it a blank white page or a blank page on your site? The url entered into the Redirect URL should be where the user is sent once the quiz has been submitted.

**Comment by PhilSil** [comment]
I have a quiz on my landing page. (example.de) After the quiz is done, the URL shown in the browser is example.de. But the page is just blank. Nothing there, just white.

**Comment by fpcorso** [comment]
Interesting.. the url field takes a complete url such as http://example.de    Is that how you have your url entered on the Result Pages tab?

**Comment by PhilSil** [comment]
Yes I tried http://example.de, example.de and also just /. Same results...
