### ISSUE TITLE
Certificate link is broken for some in emails

### ISSUE THREAD

**Issue by gamekid88** [fpcorso/quiz_master_next#239]
Sometimes when a user is emailed a certificate link it does not allow them to click on it to see their certificate. It might have something to do with Wordpress being in a subfolder. 

"file_put_contents(../wordpress/wp-content/plugins/quiz-master-next/includes/certificates/mlw_qmn_quiz20150413232954admin.php): failed to open stream: No such file or directory in /home/garrisonrr/public_html/wordpress/wp-content/plugins/quiz-master-next/includes/qmn_results_details.php on line 194 "

**Comment by fpcorso** [comment]
Alright...I think I have fixed it this time....
