### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by PhilSil** [fpcorso/quiz_master_next#247]
I get a lot of incorrect results. Therefore I will not be able to use the plugin at the moment. Can you provide a fix for that fast?

Here is an example: 

Quiz Ergebnisse für Datensicherheit

Name: Hannah 

Email: None 

Score: 12/15 or 80% or 0 points  <--- SCORE IS NOT CORRECT
Antworten:

The user took 454 to complete quiz. 

Comments entered were: 

The answers were as follows: 

Ergebnis: 

Informationssicherheit meint Eigenschaften von Systemen, Daten nur __________ ungeändert und vertraulich bereitzustellen. 
Deine Antwort: verschlüsselt 
Richtige Antwort: Befugten
Ergebnis: 

Dies minimiert wirtschaftliche und persönliche Schäden. __________ regeln internationale Industrienormen umfänglich. 
Deine Antwort: Praktische Datensicherheit 
Richtige Antwort: Praktische Datensicherheit
Ergebnis: 

Das __________ genutzte Internet prägt seit über zwei Jahrzehnten unser Leben. Es erstaunt, dass Datensicherheit trotz Normierung und technischer Entwicklungen noch unreif wirkt.

Deine Antwort: kommerziell 
Richtige Antwort: kommerziell
Ergebnis: 

Anscheinend verliefen __________ rascher als ihre Absicherung. 
Deine Antwort: digitale Revolutionen 
Richtige Antwort: digitale Revolutionen
Ergebnis: 

Tatsächlich stellen wir zur Datensicherheit deutliche __________ der Politik fest. 
Deine Antwort: Versäumnisse 
Richtige Antwort: Versäumnisse
Ergebnis: 

Als oft __________ entfaltete sich das Web ohne straffe Regeln. Solche Grenzen erzwingen sich aber für öffentliche wie individuelle Sicherheit. 
Deine Antwort: rechtsfreie Sphäre 
Richtige Antwort: rechtsfreie Sphäre
Ergebnis: 

Zum Beispiel will niemand beim Klicken auf Verweise __________ kaufen. 
Deine Antwort: unwissentliche Erbos 
Richtige Antwort: unwissentlich Abos
Ergebnis: 

Doch unbeschwertes Besuchen von Seiten im Web birgt diese __________. 
Deine Antwort: Gefahren 
Richtige Antwort: Gefahren
Ergebnis: 

Nur zögerlich begannen Vertreter der Regierung mit __________ zum Schutz von Nutzern des Internets. 
Deine Antwort: Maßnahmen 
Richtige Antwort: Maßnahmen
Ergebnis: 

Heute bemerken Surfer sogar, dass gerade die __________ ihre Bürger per Internet ausspäht. 
Deine Antwort: Regierung 
Richtige Antwort: Regierung
Ergebnis: 

Die __________ auf Vorrat unterstützt dabei weitgehende Einblicke. 
Deine Antwort: Datenspeicherung 
Richtige Antwort: Datenspeicherung
Ergebnis: 

Bitte geben Sie den gesamten Satz ein.

__________ 
Deine Antwort: So offenbahrt sich Behörden das Leben einzelner Menschen detailliert. 
Richtige Antwort: So offenbart sich Behörden das Leben einzelner Menschen detailliert.
Ergebnis: 

__________ erscheint das Löschen von Spuren im Web praktisch unmöglich. 
Deine Antwort: Privatleuten 
Richtige Antwort: Privatleuten
Ergebnis: 

Bitte geben Sie den gesamten Satz ein.

__________

Deine Antwort: Beispielsweise verbreiten sich persönliche Bilder auf öffentlichen Seiten ungehemmt. 
Richtige Antwort: Beispielsweise verbreiten sich persönliche Bilder auf öffentlichen Seiten ungehemmt.
Ergebnis: 

Bitte geben Sie den gesamten zweiten Satz ein.

Insgesamt gewinnt umsichtiges Surfen also weiterhin enorm an Bedeutung. __________ 
Deine Antwort: Nutzer begreifen zunehmend ihre Verantwortung für ihre eigene Sicherheit im Netz. 
Richtige Antwort: Nutzer begreifen zunehmend ihre Verantwortung für ihre eigene Sicherheit im Netz.

**Comment by fpcorso** [comment]
Greetings @PhilSil 
Thank you for creating an issue. I need some more information to determine if this is an actual bug. The score of 80% is indeed correct since the user answered 12 of the 15 questions correctly. Is your quiz set up for Correct/Incorrect or Points? You seem to be using both in the results page you listed here. Usually, it is one or the other.

How many points are you giving each of these answers? How many points should be listed? How do you have your results pages created? Can you copy and paste the results page template here or create a screenshot for us?

**Comment by PhilSil** [comment]
Hi @fpcorso 

Correct should be 14/15. This problem occures very often, this is just one example. I can provide more if it helps.

Quiz is set up for Correct/Incorrect.

"Du hast %AMOUNT_CORRECT% korrekte Antworten abgegeben.

%QUESTIONS_ANSWERS%"

![image](https://cloud.githubusercontent.com/assets/12174656/8273213/26b51e12-1863-11e5-8018-52b648276fca.png)

**Comment by fpcorso** [comment]
@PhilSil 

I believe that you may be mistaken. I looked over the results that you copied in and there are indeed 3 incorrect answers.

First:
Deine Antwort: verschlüsselt 
Richtige Antwort: Befugten

Second:
Deine Antwort: unwissentliche Erbos 
Richtige Antwort: unwissentlich Abos

Third:
Deine Antwort: So offenbahrt sich Behörden das Leben einzelner Menschen detailliert. 
Richtige Antwort: So offenbart sich Behörden das Leben einzelner Menschen detailliert.


These three show an answer that is different than the correct answer. Which results in 3 wrong answers. This leads to 12 correct answers which gives us 12/15 or 80%.

Can you provide another example?

**Comment by PhilSil** [comment]
Quiz Ergebnisse für Aufgeheizte Stimmung: Farbbeutelanschlag auf Bildungseinrichtung

Name: Rami 

Email: None 

Score: 12/13 or 92% or 0 points 
Antworten:

The user took 912 to complete quiz. 

Comments entered were: 

The answers were as follows: 

Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.



Unbekannte Täter verübten in der letzten Woche einen Anschlag auf die __________. 
Deine Antwort: Landeszentrale für politische Bildung 
Richtige Antwort: Landeszentrale für politische Bildung
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Die Polizei teilte mit, dass das Gebäude der __________ in der Nacht zu Donnerstag mit mehreren Farbbeuteln beworfen worden war. 
Deine Antwort: staatlichen Bildungseinrichtung 
Richtige Antwort: staatlichen Bildungseinrichtung
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


__________ 
Deine Antwort: Außerdem seien einige Fensterscheiben zu Bruch gegangen. 
Richtige Antwort: Außerdem seien einige Fensterscheiben zu Bruch gegangen.
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Der Innenminister besichtigte höchstpersönlich den Tatort in der __________ und bezifferte den Schaden auf schätzungsweise 10.000 Euro. 
Deine Antwort: Landeshauptstadt 
Richtige Antwort: Landeshauptstadt
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


__________ allem der offenkundig politisch motivierte Hintergrund des Angriffs gegen eine überparteiliche Institution. 
Deine Antwort: Ihn bewege, so der Minister, vor 
Richtige Antwort: Ihn bewege, so der Minister, vor
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Nach dem aktuellen Stand der Ermittlungen sei noch unklar, welcher politischen Strömung die Täter angehören, die kein __________. 
Deine Antwort: Bekennerschreiben hinterließen 
Richtige Antwort: Bekennerschreiben hinterließen
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


In den letzten Monaten hatte sich die Landeszentrale im Rahmen ihrer Kampagne „__________“ für eine verstärkte Teilhabe der Bürger an der politischen Diskussion eingesetzt. 
Deine Antwort: Demokratie stärken 
Richtige Antwort: Demokratie stärken
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Unter anderem wurden ihre Räumlichkeiten für eine Pressekonferenz von __________ zur Verfügung gestellt. 
Deine Antwort: Islamkritikern 
Richtige Antwort: Islamkritikern
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



In der Öffentlichkeit war dem Leiter der Einrichtung daraufhin vorgeworfen worden, er habe das Gebot der __________ massiv verletzt. 
Deine Antwort: Überparteilichkeit 
Richtige Antwort: Überparteilichkeit
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Die Landeszentrale erklärte, dass die __________ keinerlei Auswirkungen auf die laufende Arbeit haben werde. 
Deine Antwort: Attacke 
Richtige Antwort: Attacke
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.

**Comment by fpcorso** [comment]
@PhilSil Hmmm...this one says there are 13 total questions but I only see 10. Did you copy over the entire results? Can you provide a link to this quiz?

**Comment by PhilSil** [comment]
@fpcorso 
Sorry, here is the full text and a link to the quiz:
http://polizei-diktat.de/quiz/aufgeheizte-stimmung-farbbeutelanschlag-auf-bildungseinrichtung/

The user took 912 to complete quiz. 

Comments entered were: 

The answers were as follows: 

Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.



Unbekannte Täter verübten in der letzten Woche einen Anschlag auf die __________. 
Deine Antwort: Landeszentrale für politische Bildung 
Richtige Antwort: Landeszentrale für politische Bildung
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Die Polizei teilte mit, dass das Gebäude der __________ in der Nacht zu Donnerstag mit mehreren Farbbeuteln beworfen worden war. 
Deine Antwort: staatlichen Bildungseinrichtung 
Richtige Antwort: staatlichen Bildungseinrichtung
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


__________ 
Deine Antwort: Außerdem seien einige Fensterscheiben zu Bruch gegangen. 
Richtige Antwort: Außerdem seien einige Fensterscheiben zu Bruch gegangen.
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Der Innenminister besichtigte höchstpersönlich den Tatort in der __________ und bezifferte den Schaden auf schätzungsweise 10.000 Euro. 
Deine Antwort: Landeshauptstadt 
Richtige Antwort: Landeshauptstadt
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


__________ allem der offenkundig politisch motivierte Hintergrund des Angriffs gegen eine überparteiliche Institution. 
Deine Antwort: Ihn bewege, so der Minister, vor 
Richtige Antwort: Ihn bewege, so der Minister, vor
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Nach dem aktuellen Stand der Ermittlungen sei noch unklar, welcher politischen Strömung die Täter angehören, die kein __________. 
Deine Antwort: Bekennerschreiben hinterließen 
Richtige Antwort: Bekennerschreiben hinterließen
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


In den letzten Monaten hatte sich die Landeszentrale im Rahmen ihrer Kampagne „__________“ für eine verstärkte Teilhabe der Bürger an der politischen Diskussion eingesetzt. 
Deine Antwort: Demokratie stärken 
Richtige Antwort: Demokratie stärken
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Unter anderem wurden ihre Räumlichkeiten für eine Pressekonferenz von __________ zur Verfügung gestellt. 
Deine Antwort: Islamkritikern 
Richtige Antwort: Islamkritikern
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



In der Öffentlichkeit war dem Leiter der Einrichtung daraufhin vorgeworfen worden, er habe das Gebot der __________ massiv verletzt. 
Deine Antwort: Überparteilichkeit 
Richtige Antwort: Überparteilichkeit
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Die Landeszentrale erklärte, dass die __________ keinerlei Auswirkungen auf die laufende Arbeit haben werde. 
Deine Antwort: Attacke 
Richtige Antwort: Attacke
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Eine Veränderung des Bildungsprogramms wolle man sich nicht aufzwingen lassen, sagte eine __________. 
Deine Antwort: Referatsleiterin 
Richtige Antwort: Referatsleiterin
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Man werde sich einem Diktat radikaler __________ keinesfalls unterwerfen. 
Deine Antwort: Gewalttäter 
Richtige Antwort: Gewalttäter
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.


Die Veranstaltungen der __________ sollten bereits am Abend nach dem Anschlag plangemäß stattfinden. 
Deine Antwort: Bildungsinstitution 
Richtige Antwort: Bildungsinstitution

**Comment by fpcorso** [comment]
Hmmm....I just took the quiz using the correct answers from this and it says
"Du hast 13 korrekte Antworten abgegeben."

When you view my results in the admin, does it show 13/13?

**Comment by PhilSil** [comment]
@fpcorso I sent you an E-Mail with additional information, maybe you can take a look. In your case the result was correct.
