### ISSUE TITLE
Export > timestamp

### ISSUE THREAD

**Issue by rvandepu** [fpcorso/quiz_master_next#248]
Hi,

I bought the 'export results' plugin for QMN but noticed it lacks the functionality to export the timestamp when the quiz was taken. Is it possible to add this functionality?

Thanks,
Ruben.

**Comment by fpcorso** [comment]
Hey Ruben! This repository is for the core version of the plugin only. The Export Results addon is not included in this repository. However, we have already added this requested feature to our issues in our private repository for that addon and are hoping to have an update available soon with that feature.

**Comment by rvandepu** [comment]
Hi Frank,

Regarding this ticket:
https://github.com/fpcorso/quiz_master_next/issues/248.
Was this feature already added to the add-on?

Thanks for your reply.
Ruben Van de Put

2015-06-26 20:12 GMT+02:00 Frank Corso <notifications@github.com>:

**Comment by fpcorso** [comment]
Hey Ruben,

We are still working on the Export Results addon update but are in the final testing phases now. It should be available within the next 2 weeks.
