### ISSUE TITLE
Still getting incorrect results

### ISSUE THREAD

**Issue by PhilSil** [fpcorso/quiz_master_next#265]
Hi,
I am still getting incorrect results. My customers go wild. Please provide a fix for me. 
I could provide tons of examples:

Quiz Ergebnisse für Jungen Straftätern eine Chance geben
Email: None

Score: 9/12 or 75% or 0 points
Antworten:

The user took 10353 to complete quiz.

Comments entered were:

The answers were as follows:

Bitte das fehlende Wort eingeben.

Wenn es um das Thema __________ geht, dann scheiden sich die Geister.
Deine Antwort:     Graffiti
Richtige Antwort: Graffiti
Bitte das fehlende Wort eingeben.

Handelt es sich dabei nun um Kunst oder um __________?
Deine Antwort:     Vandalismus
Richtige Antwort: Vandalismus
Bitte das fehlende Wort eingeben.

Die Besitzer der Objekte, die mit den kreativen __________ Jugendlicher versehen werden, brauchen in der Regel nicht lange, um diese Frage zu beantworten.
Deine Antwort:     Exzessen
Richtige Antwort: Exzessen
Bitte ergänzen Sie die fehlenden Wörter mit Komma, falls nötig.

Für sie ist der Fall klar. __________ welches man nicht einfach ungestraft durchgehen lassen kann.
Deine Antwort:     Sachbeschädigung ist ein Delikt,
Richtige Antwort: Sachbeschädigung ist ein Delikt,
Bitte das fehlende Wort eingeben.

Von den __________ wird entsprechend erwartet, dass sie ihre Arbeit tun, die Schuldigen finden und zur Rechenschaft ziehen.
Deine Antwort:     Ordnungshütern
Richtige Antwort: Ordnungshütern
Bitte das fehlende Wort eingeben.

Doch was bewegt junge Menschen eigentlich dazu, __________ zu besprühen?
Deine Antwort:     Hauswände
Richtige Antwort: Hauswände
Bitte das fehlende Wort eingeben.

Während einige keinen anderen Weg sehen, um ihre Ideen auch einem größeren Publikum zugänglich zu machen, überwiegt für andere der Reiz des __________.
Deine Antwort:     Verbotenen
Richtige Antwort: Verbotenen
Bitte ergänzen Sie die fehlenden Wörter.

Grenzen zu überschreiten und auf diese Weise gegen überkommene Regeln zu protestieren, sind __________.
Deine Antwort:     Grundaspekte von Demonstrationen
Richtige Antwort: Grundaspekte von Demonstrationen
Bitte ergänzen Sie dir fehlenden Wörter.

Wenn dabei jedoch andere Menschen oder ihr __________, dann hört der Spaß auf.
Deine Antwort:     Eigentum zu Schaden kommen
Richtige Antwort: Eigentum zu Schaden kommen
Bitte das fehlende Wort eingeben.

Viele Pädagogen und Psychologen sehen in dem Phänomen eine extreme Form der Pubertät, in welcher Jugendliche lernen müssen, sich mit sich selbst und ihrer Umwelt __________, um ihren eigenen Weg zu finden.
Deine Antwort:     auseinanderzusetzen
Richtige Antwort: auseinanderzusetzen
Bitte das fehlende Wort eingeben.

Für sie liegen die Ursachen für dieses Verhalten im __________ und in der Gesellschaft.
Deine Antwort:     Elternhaus
Richtige Antwort: Elternhaus
Bitte das fehlende Wort eingeben.

Sie raten dazu, __________ gewordenen Jugendlichen die Möglichkeit zu geben, sich beispielsweise im Rahmen eines Straßenkunst-Projektes auf legale Weise kreativ auszuleben.
Deine Antwort:     auffälig
Richtige Antwort: auffällig

**Comment by fpcorso** [comment]
This is a duplicate of #247 which is still open and we are still working on resolving. Please continue to use that issue for further examples.
