### ISSUE TITLE
Add new doesn't work

### ISSUE THREAD

**Issue by MikaDel** [fpcorso/quiz_master_next#268]
I just installed the plugin BUT I can't create a quiz, the button "add new" doesn't respond...
There is no link on that button :(

Please help,

Thanks,

Mika

**Comment by fpcorso** [comment]
To best diagnose the issue that you are experiencing, please follow the "Create A Issue" section of the Contributing guidelines so we can have the information needed to debug the issue.

([Create An Issue Guidelines](https://github.com/fpcorso/quiz_master_next/blob/master/CONTRIBUTING.md#creating-issues))

**Comment by fpcorso** [comment]
Hey @MikaDel, I haven't heard from you with the information needed to debug this issue. I am going to close this issue for now. Feel free to post here when you are available or if you still need assistance.
