### ISSUE TITLE
Ability to upload file before submitting

### ISSUE THREAD

**Issue by Dysschord** [fpcorso/quiz_master_next#283]
I have need of users being able to upload a file before submitting their (in this case) survey. Could this be possible in a future release?

**Comment by fpcorso** [comment]
Hey @dysschord! I can definitely add this to the list of requested features for you. Can you elaborate a little more on what kind of file the users will be uploading for the survey?

**Comment by Dysschord** [comment]
My surveys will include a call for papers, so documents (doc, docx, rtf and
txt). Thanks!

**Comment by fpcorso** [comment]
Duplicate of #242. Both are needing file upload.
