### ISSUE TITLE
I want to place direct question don't need next button before question

### ISSUE THREAD

**Issue by Umer-Shoukat** [fpcorso/quiz_master_next#289]
Hi!
When i place short code on page and preview. It shows welcome message and then next button. then it shows questions .. but i don't want that next button i just want to post direct questions on the page and a submission button that's it. kindly help me out in modifying this problem. Thanks .

**Comment by fpcorso** [comment]
Discussion for this is in our support topic here: https://wordpress.org/support/topic/i-want-to-place-direct-question-dont-need-next-button-before-question
