### ISSUE TITLE
Required questions not working properly

### ISSUE THREAD

**Issue by markavickers** [fpcorso/quiz_master_next#292]
I had all my questions marked as required.  Now when a user takes the survey, the only question that is actually required is the last one on the page.  

If I edit the questions, they all show NO for required.  If I change it to yes and save, it does not change.

Please help... I have users skipping critical questions.

Thanks

**Comment by fpcorso** [comment]
Discussing in email now...

Possible pagination issue.

**Comment by steknef** [comment]
I have the same problem...can you help me to solve this please?

**Comment by fpcorso** [comment]
Duplicate of #395
