### ISSUE TITLE
No Emails Being Sent

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#30]
Several users are experiencing an issue where no emails are being sent even though either user email is set to yes or admin email is set to yes or both.

**Comment by SangameshPH** [comment]
Hi fpcoso,
Any update on this bug? :)
Cheers,
-/Sammi

**Comment by fpcorso** [comment]
@SangameshPH This tends to be more of a case by case since most users are experiencing this for a variety of reasons. I have most of the reasons that were causing this bug fixed though there are a few that are still experiencing some intermittent issues.

**Comment by fpcorso** [comment]
Since this appears to be rare with each case being a unique situation, I am going to go ahead and close this.
