### ISSUE TITLE
multi-address admin emails, rejected by some mail servers

### ISSUE THREAD

**Issue by philbuh** [fpcorso/quiz_master_next#312]
On the edit quiz > emails tab you can enter the email address(es) for admins: "What emails should we send the admin email to? Separate emails with a comma."

This generates a valid multi-address email From: header, which works with most mail servers.

Some mail servers, e.g. yahoo.co.uk, will reject this as non-RFC5322 compliant.  RFC5322 ( https://tools.ietf.org/rfc/rfc6854.txt ) mandates a single-address Sender: header when using a multi-address From: header.

**Comment by philbuh** [comment]
I tried modifying the code to add the Sender: header, arbitrarily using the first admin From: address, but it appears both the "wp_mail" and generic "mail" functions will silently strip the header beforesending.

**Comment by fpcorso** [comment]
Ah, I almost mis-understood the issue. I had a whole comment written out and started looking into it but I thought you meant the To field even though you specifically said From field.

Anyways, in the version I am testing right now (4.6.0), I create a new field where you can enter in the From address specifically. So, it will not use the multi-address entered into the admin emails field. That should take care of this issue.

**Comment by fpcorso** [comment]
Hey @philbuh! Can you update to version 4.6.0 or later and configure using the new From address option? Let me know if you are still having this issue.

**Comment by philbuh** [comment]
I've given it a thrashing, seems to work fine now.  

I saw the original issue with hotmail.co.uk addresses as well, btw.
