### ISSUE TITLE
Results Analysis addon: Pie chart display issues

### ISSUE THREAD

**Issue by joojaadvertising** [fpcorso/quiz_master_next#314]
There's an issue with the pie chart displays when viewing the quiz results analysis using the Results Analysis addon. Sometimes, an answer does not have a colour assigned to it, and it just takes on the same colour as the previous answer.
![screen shot 2015-10-20 at 4 11 51 pm](https://cloud.githubusercontent.com/assets/15209718/10601865/34b3eee2-7747-11e5-8b5e-452efdc86d65.png)

**Comment by fpcorso** [comment]
Hey @joojaadvertising! Thanks for letting me know about this. I actually have a separate repo for that addon that is private at the moment. I went ahead and re-created your issues there so my developers and I will see them as we work on the next version. I'll try to get an update out soon to address this color issue you describe here. There are a few other issues with the charts that I want to take care of such as adding the value in the legend and cleaning up the spacing too. Thanks again!
