### ISSUE TITLE
Results Analysis addon: Export results analysis to PDF

### ISSUE THREAD

**Issue by joojaadvertising** [fpcorso/quiz_master_next#315]
Would be great if there was a feature to export the results analysis to a pdf, or restyle the piecharts so that the figures can be read from a printout. Thanks!

**Comment by fpcorso** [comment]
Hey again! Exporting as PDF is probably the most requested feature for that addon. I went ahead and gave you access to the private repository. I think your ideas and feedback are great! So feel free to create some issues over in the repo for this addon if you have any more feedback.
