### ISSUE TITLE
%QUESTIONS_ANSWERS% works in email template but not %QUESTION%, %USER_ANSWER% etc

### ISSUE THREAD

**Issue by quadrigal** [fpcorso/quiz_master_next#342]
Hi There

In the email templates I can't get the placeholders:

%QUESTION%
%USER_ANSWER%
%CORRECT_ANSWER%

...to work. However %QUESTIONS_ANSWERS% works fine. Problem is I don't use the question comment functionality so don't want it to appear in the results email- so I want to use the individual elements, question and answer.

**Comment by fpcorso** [comment]
Greetings @quadrigal,

Thank you for choosing to use this plugin! The issue tracker for this plugin is not the place for support. You can edit the %QUESTIONS_ANSWERS% variable on the "Text" tab by editing the %QUESTIONS_ANSWERS% Text option where you can remove the comments. The %QUESTION%
%USER_ANSWER%, %CORRECT_ANSWER% variables only work inside that option.
