### ISSUE TITLE
Redirect To Other Page Upon Completion

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#35]
User wants to redirect quiz takers to new page after completing quiz

**Comment by OC2PS** [comment]
Check out screenshot 6 (routes) here: https://wordpress.org/plugins/wordpress-simple-survey/screenshots/

**Comment by fpcorso** [comment]
@OC2PS Yes, I am planning something similar to that. I was thinking of adding a "route" field or similar to the results page tab. I would have it next to the textarea. If the admin has a url entered, then the user is redirected instead of being shown what is in the box. This feature is marked for version 4.2.0.

**Comment by fpcorso** [comment]
Added Redirect Functionality In #156
