### ISSUE TITLE
Question Grouping

### ISSUE THREAD

**Issue by AssaultOuStudios** [fpcorso/quiz_master_next#356]
I was looking for a way in which to group specific questions - it seems there isn't really an option to do this now. I'd like for example to have a heading, with 5 sub questions and another heading with 8 sub questions etc. each separated in their own block elements.

Because of the different amount of questions per block, pagination won't really work for me. In terms of design it's really untidy and un-user-friendly if there are a hundred questions stacked underneath one another. So really all I'm trying to do is get some items into a single div so I can style them as a block - just to give it a bit of separation.

Other than that, great plugin. I've found it's the best of its type available - keep up the good work!

**Comment by fpcorso** [comment]
Hey @AssaultOuStudios 
Thank you for choosing to use this plugin! I think this would definitely be a useful idea. Let me ponder this over to see how I may be able to implement this.

**Comment by fpcorso** [comment]
The new editor and rendering system has been merged into the 5.2 release. This new version allows users to create pages and group questions in whatever way the user needs.
