### ISSUE TITLE
Deleting a quiz breaks quizzes with the same name

### ISSUE THREAD

**Issue by ty2u** [fpcorso/quiz_master_next#357]
If I delete Quiz 1 and then create Quiz 1 then the new Quiz 1 does not work due to a conflict in the name of the quiz. I suspect this is due to the sql query also going by the quiz name which it probably shouldn't be necessary since the id should be unique.

**Comment by fpcorso** [comment]
Hey @ty2u! When you say that the new Quiz 1 does not work, does it still work on the Preview tab? Where is it breaking at? When you click View Quiz or when using the shortcode or both?

All the queries to the quiz is by the quiz_id primary column so it shouldn't be a conflict due to name. If the quiz seems to be only breaking at the View Quiz link and works everywhere else, there may be an issue in the permalinks/post_meta system I use to assign created quizzes to the quiz post.

I'll have to test this out in a day or so to see if I can duplicate it and get to the bottom of it. Thanks for reporting!

**Comment by ty2u** [comment]
I believe it actually does work on the preview tab. What doesn't work is when I go to the URL /quiz/quiz-1/ which I am using to display the quiz through an iframe in a slideout when they click a button. So it's just linked to the old post still I suppose and therefore the correct URL would then be something more like /quiz/quiz-1-2/ or something of that nature.

However, things get messed up in the database somehow because there is an error 0003 as well after when I try to rename the new quiz which every time it happens creates another post object for the error.

**Comment by fpcorso** [comment]
Hmmm... @ty2u I am still having trouble replicating this error. When you click on the "View Quiz" link on your new Quiz 1, what happens?

Also, for the error 0003, can you send me the contents of the post so I can see what the sql error returned was?

**Comment by ty2u** [comment]
Sorry for the trouble.

Actually, that's another weird thing. Sometimes the View Quiz link does 
not appear. It's like it only shows for the 10 most recently created 
quizzes. So that's why I didn't know the link would have changed at 
first until I went digging in the database and whatnot. But what 
happened is that when I went to the old link it was the wrong quiz and 
it took me a bit to realize that.

I will do some more testing on a copy of the site some time when I get a 
chance and give you a step by step way to reproduce it. I no longer have 
those posts or quizzes in the database since I had to start fresh with 
everything to get it to work again. I actually have now hidden the 
delete link so people don't click it so that we don't have conflicts. 
But basically it was an issue with the fact that the deleted quiz had 
the same name as the new quiz and possibly the fact that it doesn't 
rename the post name/slug to the new URL. I have permalinks set to post 
name. What might fix this is if I could have the option to permanently 
delete the quiz at the time of deletion, including it's questions, and 
it's post and possibly optionally the results, so that I can start fresh 
without conflicts.

I will reproduce it for you hopefully at some point today or tomorrow 
and give you all the details you want and anything else that I can.

**Comment by ty2u** [comment]
Sorry this has taken me so long to get to. Was really busy.

I tried to duplicate the issue after updating to 4.6.7 but was unable to.

Now when I delete and then duplicate or even create a new quiz with the same name as the deleted one then it renames the slug properly adding a -2 to the end of it and even a -3 if I duplicate/create it again.

Maybe something in one of your updates fixed it or maybe there was some other weird stuff going on which is no longer going on.

If I come across it again I will definitely let you know, although there is a very slim chance of that since I've hidden the delete link =)

**Comment by fpcorso** [comment]
No worries @ty2u. I'll go ahead and close out this issue for now but if you encounter it again, simply comment here.
