### ISSUE TITLE
Number of tries not properly output

### ISSUE THREAD

**Issue by ty2u** [fpcorso/quiz_master_next#360]
Even when I set the number of tries to 2, and even though both tries go through properly, afterwards it says I'm only allowed 1 try:

You are only allowed 1 try and have already submitted your quiz.

BTW, these are Version 4.6.6

**Comment by fpcorso** [comment]
Hey @ty2u. If you edit your quiz and go to the Text tab, what do you have entered into the option labelled "Message Displayed If User Has Tried Quiz Too Many Times "?

**Comment by ty2u** [comment]
Ahh, didn't realize it was a message template. Thanks
