### ISSUE TITLE
email not sending to user and admin

### ISSUE THREAD

**Issue by marioloncarek** [fpcorso/quiz_master_next#368]
I have the option for sending emails to admin and to one who take the test. **Neither email is sent**. I checked spam folder. Admin email is gmail. 
Switched to the default theme (twenty sixteen, twenty fifteen tested) - **Still not working**
De-activate all other plugins, deleted all other plugins - **Still not working**
Tested on **Chrome, Firefox, Edge, IE 11**

Wordpress Version 4.4.1 - installed **LOCALLY (localhost)**.  Gmail SMTP configuration
Latest version of QMN - 4.6.7
Windows 10

Thanks in advance!

**Comment by marioloncarek** [comment]
Im sorry, this is not a plugin error, gmail was blocking my SMTP connection with localhost. Now made a test on server, everything works as expected.

**Comment by fpcorso** [comment]
Hey @marioloncarek. Thank you for choosing to use this plugin! Sorry for not getting back to you sooner. How did you discover the cause of the issue?

**Comment by marioloncarek** [comment]
@fpcorso Gmail sent me an error message that is now blocking my connection, so no emails were getting trough. 
BTW Thank you for making this plugin, im now testing it for a few days, must say its great! Keep it up
