### ISSUE TITLE
Ability to add check box for privacy statement with the contact fields

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#372]
In Italy, it is mandatory to have a checkbox with some privacy text and link to privacy document when collecting user contact information. So, I need to add the ability to place this near the contact fields to make it easier for admins as opposed to having to use an "Accept" question type within the questions. Quizzes that are set up using pagination would not show the "Accept" question at the same time that the contact information is being collected.

**Comment by neuroine** [comment]
Is there some way to help create such functionality?

**Comment by fpcorso** [comment]
Created in most recent commit for 5.0 update
