### ISSUE TITLE
Export to csv not working

### ISSUE THREAD

**Issue by Jimtowner** [fpcorso/quiz_master_next#374]
I purchased the Analytics plug in. When I click "Export as CSV" after "Analysis Quiz Results" nothing happens. How can I get the export to work?

Thanks.

**Comment by fpcorso** [comment]
Hey @Jimtowner! This is the repo for the core plugin and not for any of the addons. Can you submit a support ticket here: http://quizandsurveymaster.com/contact-us/  so that I can assist you and look into this further.
