### ISSUE TITLE
Rewrite results pages to allow for different conditions

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#378]
Right now, the results pages can only be shown based on total score or default. It also shows both redirect and results page options.

This new system will allow users to create a "result page" or "redirect". Then, the user will be able to select the conditions that must be true to activate that results page or redirect.

For example, when user clicks "Add New Results Page", they could select conditions of "total score less than:" 30 points and "total score greater than: " 0 points to get a setup similar to the existing. However, in the conditions, we can also include "category score less than", "category score greater than", "question ___ answered as: ", etc.. which will allow much more flexibility in results pages.

**Comment by jor216** [comment]
Was this feature ever added?
