### ISSUE TITLE
Rewrite emails to allow for different conditions

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#379]
Like mentioned in #378, we need to update the results pages and emails to allow much more flexibility. These updates will allow users to send different emails based on scores in categories or even which answer was given for a certain question.

**Comment by katarinadjordjevic1** [comment]
Hi, I installed the latest version of QSM (6.4.5), but I still don't see the option to set the condition based on points in a specific category. I only have option to set a condition based on total score, do you know what might be the issue with this? Thank you in advance :)

**Comment by jor216** [comment]
Was this feature ever added?

**Comment by diksha825** [comment]
Hi @jor216 

Unfortunately we dont have this feature in QSM. We have escalated your request to the team.

**Comment by jor216** [comment]
Thanks for your reply. I would be willing to pay for its development. Is
there someone I can connect with on this?

Jolawn Victor

**Comment by diksha825** [comment]
@jor216 I have submitted your request and one of our support team members would contact you shortly. Our team can be contacted at : https://justhyre.com/

**Comment by diksha825** [comment]
You can directly our support team at: https://justhyre.com/
