### ISSUE TITLE
Randomize MC Answer Choices

### ISSUE THREAD

**Issue by jmferrell** [fpcorso/quiz_master_next#383]
Frank—forgive me if this request exists already; looked but didn't see it. We discussed this much earlier, pre-GitHub, I believe:

I often give quizzes in a computer lab, and it would be nice if I could keep the Questions in a fixed order, but have multiple choice Answers shuffle.

**Comment by fpcorso** [comment]
Hey @jmferrel! There is an issue that I created when we discussed this previously which is issue #330. This issue is scheduled to be added in 4.7.0 which I am hoping to have out at the beginning of next week.

**Comment by jmferrell** [comment]
Ugh, sorry. I was SURE it had to be in here somewhere, but I couldn't find it. :(
