### ISSUE TITLE
Overlap of horizontal multiple choice questions

### ISSUE THREAD

**Issue by dabl99** [fpcorso/quiz_master_next#393]
I have previously had an overlap of horizontal multiple choice questions and the radio button answers. Have overcome it by inserting a return character before each question line.   Now I find the problem has come back. I have tried pasting the recommended code solution into the style tab coding without any success.  I am using Twentyfourteen and my site is dpbridgeteaching.com.  I have gone back to a backup done a week ago and it seems ok. Within the week I added a couple of quizzes and edited a few others.
Daniel Phelan

**Comment by fpcorso** [comment]
Hey @dabl99 Please create a support ticket using this form to receive support on this issue: http://quizandsurveymaster.com/contact-us/

This issue tracker is for feature requests and known bugs.
