### ISSUE TITLE
no radio buttons

### ISSUE THREAD

**Issue by yafittau** [fpcorso/quiz_master_next#405]
Hi!

Thanks for the great plugin! 
I have 1 bug though, that I hope you can help me with - the radio buttons are almost unseen, making it very hard to understand how to answer the questions. How can I fix this?

Thanks!

![2016-04-10_2132](https://cloud.githubusercontent.com/assets/18381613/14412131/e04a4e28-ff63-11e5-8bfb-51221e455a5d.png)

**Comment by fpcorso** [comment]
Hey @yafittau Usually, this is caused by a CSS conflict with your theme. Can you create a support ticket using the form on "Help" page in the "Quizzes/Surveys" menu so that our support team can assist you debugging this further?
