### ISSUE TITLE
Progress Bar 

### ISSUE THREAD

**Issue by dukeran** [fpcorso/quiz_master_next#412]
User requested to have a progress that indicates how many questions left and/or the percentage until completion

**Comment by fpcorso** [comment]
I could have sworn that I created an issue for this request before but I can't find it now. I know that at least one other person has requested this previously.

**Comment by dukeran** [comment]
I looked for it as well but couldn't find anything. It was a request in the forums of wordpress.org, seems like a good idea!

**Comment by fpcorso** [comment]
Another user has requested this feature.
