### ISSUE TITLE
Answers containing apostrophes not evaluated

### ISSUE THREAD

**Issue by jmferrell** [fpcorso/quiz_master_next#421]
I'm not sure why I haven't run into this yet, but it bit me in a huge way with my most recent quiz:

As far as I can tell (with some, but not extensive testing), multiple choice answer choices containing an apostrophe (or single quote) are not evaluated or matched when a quiz is submitted. 

Example:

[x] This answer's correct.
[  ] This one's incorrect.
[  ] This answer is also incorrect.

Produces a score of 0 and %QUESTIONS_ANSWERS% outputs:
Answer provided:
Correct answer: This answer's correct.

[  ] This answer's correct.
[x] This one's incorrect.
[  ] This answer is also incorrect.

Produces a score of 0 and %QUESTIONS_ANSWERS% outputs:
Answer provided:
Correct answer: This answer's correct.

[  ] This answer's correct.
[  ] This one's incorrect.
[x] This answer is also incorrect.

Produces a score of 0 and %QUESTIONS_ANSWERS% outputs:
Answer provided: This answer is also incorrect.
Correct answer: This answer's correct.

This seems so basic, I can't think I'm the first to spot it, but a quick search didn't turn it up. Possibly related to [#230](https://github.com/fpcorso/quiz_master_next/issues/230)?

**Comment by dukeran** [comment]
Hey jmferrell,
​
Thank you for choosing to use our plugin!
​
To help us debug this issue, can you submit the Support Form within the plugin which will send us useful data about your WordPress installation including PHP version, WordPress version, active plugins, etc... You can find this form on the Help page in the Quizzes/Surveys menu.
​
Would you be able to perform a plugin conflict check? This process will check to see if there is a plugin that you have installed that may not be compatible with the plugin that you are trying to use. To do this, first de-activate all other plugins besides Quiz And Survey Master. Now, check to see if it is working correctly. If this fixed the problem, this suggests that it is a plugin conflict issue. To discover which plugin may contain the conflict, activate one plugin and then check if the plugin you are setting up still works. If it no longer works again, the plugin you just re-activate is the plugin conflict. If not, continue to activate the plugins one by one and check to see if the problem arises again. If you do find a plugin conflict, please let me know which plugin and which version of the plugin that you are using.
​
If a plugin conflict is not causing the issue, then we'll be able to continue correspondence through the email system the support ticket operates on and we'll work on finding a solution to the issue. 

​Cheers!

**Comment by jmferrell** [comment]
Sorry about that! Worst bug report ever! (I was in a hurry, and kind of stunned. I also forgot about the form on the Help page...if you'd prefer to wipe this from Git, feel free!)

I've disabled all my plugins except a few basics, installed a fresh copy of Quiz and Survey Master, and I can still reproduce the error. Does it not happen on your end?

Here are a few choice stats:

**Wordpress**
Version: 4.5.2
Language: en_US
Active Theme: X – Child Theme 1.0.0 /* Switched to Twenty Twelve to test */
Debug Mode: Disabled
Memory Limit: 40M 

**Active Plugins**
Amazon AWS for Wordpress: 0.5
Cornerstone: 1.2.4
No Adverts For Master Suite: 1.0
Plugin Notes: 1.6
Quiz And Survey Master: 4.7.0
UpdraftPlus - Backup/Restore: 1.12.6

**Server Info**
PHP : 5.3.28
MySQL : 5.5.48
Webserver : Apache

**Comment by fpcorso** [comment]
I believe this has been fixed for a while from #565 . @jmferrell I am going to close this but let me know if you are still having this issue.
