### ISSUE TITLE
Clicking submit causes an automatic scrolling up of the page 

### ISSUE THREAD

**Issue by dukeran** [fpcorso/quiz_master_next#428]
A user reported that when a quiz taker answers the quiz, the page scrolls up automatically to almost the middle of the page. The user has multiple one-question quizzes on one page and he would prefer to not have the page scroll up every time the taker clicks 'submit'. 

The user's link is here; http://www.megisoft.com/test-your-java-skill-beginner/

**Comment by fpcorso** [comment]
Fixed in newest commit.
