### ISSUE TITLE
Apostrophe in the Title of the Certificate doesn't work

### ISSUE THREAD

**Issue by dukeran** [fpcorso/quiz_master_next#434]
found that if a user adds an apostrophe in the 'title' section of the certificate, the certificate will run into an error

**Comment by dukeran** [comment]
User Reported: To avoid strange letters [in the title] I found that the first field must end with a period otherwise it will create some problem

**Comment by fpcorso** [comment]
Certificate functionality is moved to Certificate addon. Created relevant issue over in that repo so I am closing this one.
