### ISSUE TITLE
New Post can not Pubilsh

### ISSUE THREAD

**Issue by harishagrawala** [fpcorso/quiz_master_next#441]
Hi, Recently i had publish an new quiz [General Question Insurance Quiz](http://www.insuranceinfo.co.in/quiz-exam/general-question-insurance-quiz/) on my site, after publish quiz not showing on page. i had complaint to author of  plugin, revert is still awaited. under help section in plugin i had found bugs same has been mentioned below:

QMN Recent Logs

Log created at 2016-05-25 17:28:15 : Error 0004 - from UPDATE `wp_mlw_questions` SET `question_name` = 'Which of the following types of companies/organizations issue ULIP?', `answer_array` = 'a:5:{i:0;a:3:{i:0;s:22:"Insurance companies’";i:1;d:0;i:2;i:1;}i:1;a:3:{i:0;s:13:"Stock brokers";i:1;d:0;i:2;i:0;}i:2;a:3:{i:0;s:13:"Stock brokers";i:1;d:0;i:2;i:0;}i:3;a:3:{i:0;s:3:"RBI";i:1;d:0;i:2;i:0;}i:4;a:3:{i:0;s:11:"Post office";i:1;d:0;i:2;i:0;}}', `question_answer_info` = '', `comments` = 1, `hints` = '', `question_order` = 3, `question_type_new` = '0', `question_settings` = 'a:1:{s:8:"required";i:0;}', `category` = 'General Question Insurance Quiz' WHERE `question_id` = 94

Kindly assist.

Regards
Harish

**Comment by fpcorso** [comment]
Hey @harishagrawala Thanks for choosing to use this plugin! Have you already created a support ticket using the "Help" page inside the plugin? That would help us debug this further.

**Comment by sosbuzz** [comment]
I have a similar problem, post appears on front page of website but when I click on it nothing opens?
How do I fix?
