### ISSUE TITLE
Important Bug: Results Page Won't Load 

### ISSUE THREAD

**Issue by dukeran** [fpcorso/quiz_master_next#445]
Results pages won't load for certain users 
![screen shot 2016-06-02 at 1 15 47 pm](https://cloud.githubusercontent.com/assets/12517361/15754260/7035a0d4-28c5-11e6-8343-8a9531a0de1d.png)

**Comment by guilegatan** [comment]
Same behaviour here!
WP 4.5.2, QuizMasterNext Version 4.7.3

> Missing argument 4 for QMNQuizManager::load_questions(), called in /home/content/98/7400298/html/dockner/efs-online/wp-content/plugins/quiz-master-next/php/class-qmn-quiz-manager.php on line 142 and defined in /home/content/98/7400298/html/dockner/efs-online/wp-content/plugins/quiz-master-next/php/class-qmn-quiz-manager.php on line 188

**Comment by fpcorso** [comment]
Interesting bug. This appears to only be causing an error on certain sites though I am not sure why only a few are affected. I just committed a fix and will be pushing an update out shortly.

**Comment by harishagrawala** [comment]
Hi, after submit quiz user, user can not show result page how will setup plugin on my [site](http://www.insuranceinfo.co.in/)
