### ISSUE TITLE
Questions shift 

### ISSUE THREAD

**Issue by RVS-Admin** [fpcorso/quiz_master_next#467]
Please provide the following information when creating your issues:
## General description

We have 5 questions per page. When a quiz taker goes back a screen to check their answers and then moves forward again, the questions shift so for example after going back to review questions 6 through 10, instead of seeing questions 11 through 15 on the next screen, they see questions 7 through 11. 
![2016-08-18_1533](https://cloud.githubusercontent.com/assets/21112828/17792921/a23dc636-6558-11e6-8fc3-39b885a558e2.png)
## Expected behavior

We expect the questions on each page to remain static
## Actual behavior

We have 5 questions per page. When a quiz taker goes back a screen to check their answers and then moves forward again, the questions shift so for example after going back to review questions 6 through 10, instead of seeing questions 11 through 15 on the next screen, they see questions 7 through 11. 
![2016-08-18_1533](https://cloud.githubusercontent.com/assets/21112828/17792921/a23dc636-6558-11e6-8fc3-39b885a558e2.png)
## Steps to reproduce the behavior

Once you start the quiz and move to the second screen of questions, click the back button and then move forward again. Happens every time.

**Comment by fpcorso** [comment]
The new editor and rendering system has just been merged into the release scheduled to be 5.2. This new system will allow users to create and order pages in any way they need and does not use the question itself as the ordering mechanism which caused the issue described in this issue.
