### ISSUE TITLE
Tab "result pages" doesn't appear anymore

### ISSUE THREAD

**Issue by edklijsen** [fpcorso/quiz_master_next#469]
## General description
Creating a test using the quizmaster, one works through the tabs and sets the texts and settings to make it work and look faboulous. However, when you want to create the result page (tab result pages) nothing appears anymore

## Expected behavior
Clicking the tab, a screen should appear (and did appear in the past) where the result page of a test can be designed. F.i. text editor fields.

## Actual behavior
Nothing happens when you click the tab. Just the grey screen.

## Steps to reproduce the behavior
Open Wordpress.
Click Quizes
Choose "edit quiz"
Click tab "result pages"

**Comment by fpcorso** [comment]
Hey @edklijsen Thanks for creating an issue. When you have a moment, can you fill in the description template for the issue so I can get some more details about the issue that you are experiencing?
