### ISSUE TITLE
Localization incomplete on Global Settings page

### ISSUE THREAD

**Issue by Cindio** [fpcorso/quiz_master_next#478]
## Issue

Hello, not everything in your plugin has been localized, like the Admin Settings page and the word 'Points' in scores for the leaderboard display in widgets.php. This is actually an issue for your non-English users, current and future.  I'm attaching a screenshot of the Global Settings.
![qmn-settings](https://cloud.githubusercontent.com/assets/22179659/18487920/c24e355a-79bc-11e6-950d-ceea4ecb5da6.png)

**Comment by fpcorso** [comment]
Hey @Cindio Thanks for pointing these out! I will get this corrected in the next update.

**Comment by Cindio** [comment]
Wow - you rock 'n roll!

**Comment by fpcorso** [comment]
Updated localization for Global Settings page in recent commit.
