### ISSUE TITLE
If user refreshes quiz page when timer is at 0, cannot submit

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#501]
A user sent in some feedback:

"I noticed if a quiz is timed... and the time goes to 0... and they refresh browser... timer stays at 0 and they can't retake the test... timer keeps saying zero... even if the number of times they can take the test option is set to unlimited."

**Comment by tiwari85aman** [comment]
@fpcorso i want to work on this bug to fix it, any roadmap suggested ? from where should i start any suggestions. thanks!

**Comment by fpcorso** [comment]
Fixed in a recent commit.
