### ISSUE TITLE
Fatal error: Call to a member function register_question_type

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#509]
## General description
We get reports of this error from time to time but have never had a way to replicate it. One user encountered this before and the hosting company told him to not use our plugin but was unable to replicate the issue. Essentially, in certain circumstances, the plugin crashes with this error:

`Fatal error: Call to a member function register_question_type() on null in /home/[user]/domains/[domain]/public_html/wp-content/plugins/quiz-master-next/php/question-types.php on line 14`

## Steps to reproduce the behavior
The user who reported this issue today was able to send a way to replicate this issue:

"You can easily reproduce this issue by installing your plugin in a WordPress website, then creating a file "test.php" in the root of your site, and lastly to use this command inside of that test.php:
require_once("../wp-config.php");"

I believe fixing this issue may also fix the issue relating to WP-CLI which results in a very similar error.

**Comment by fpcorso** [comment]
Note from user with image:

"I just did some testing and noticed the reproduction requires a more specific use of code. I narrowed it down to the following code which is 100% reproducible:"

![example](https://cloud.githubusercontent.com/assets/9730040/23097083/f23d4356-f5f8-11e6-939c-53ab4c085558.gif)

**Comment by zhunik** [comment]
Having same issue with WP-CLI, when running `wp core update`.

**Comment by xinomilo** [comment]
same issue with any wp-cli command : 
$ wp plugin status
PHP Fatal error:  Call to a member function register_question_type() on null in /wp-content/plugins/quiz-master-next/php/question-types.php on line 14
Fatal error: Call to a member function register_question_type() on null in /wp-content/plugins/quiz-master-next/php/question-types.php on line 14

**Comment by xinomilo** [comment]
sorry, that was latest wp-cli, with plugin version 4.7.10. with plugin version 5.0.2 error is different : 
$ wp plugin status
PHP Fatal error:  Call to a member function register_quiz_setting() on null in /wp-content/plugins/quiz-master-next/php/class-qsm-install.php on line 64
Fatal error: Call to a member function register_quiz_setting() on null in /wp-content/plugins/quiz-master-next/php/class-qsm-install.php on line 64

**Comment by stevendeeds** [comment]
I also am experiencing the issue @xinomilo is experiencing... My error on Version 5.0.6:

PHP Fatal error:  Call to a member function register_quiz_setting() on null in /wp-content/plugins/quiz-master-next/php/class-qsm-install.php on line 64

**Comment by iamdonut** [comment]
Same issue here regarding the use of WP CLI. It seems that the global $mlwQuizMasterNext variable is never explicitly defined as such. Adding the global declaration ("global $mlwQuizMasterNext") immediately before the instantiation of the main class (at the bottom of mlw_quizmaster2.php) cleared up the errors for me. I've grepped around a bit within the plugin's code and am honestly not even sure how it's working via normal page requests, but I'm glad to have WP CLI working again without having to disable the plugin.

**Comment by rklrkl** [comment]
Just a note that I'm seeing this issue with WP-CLI as well and since that's the way we update sites, the breakage means I have to put iamdonut's fix in mlw_quizmaster2.php each time there's an update (there's been 3 releases since his comment, none of which have included the fix). Just to make it clear, this is how the bottom of my modified mlw_quizmaster2.php now looks:

global $mlwQuizMasterNext;
$mlwQuizMasterNext = new MLWQuizMasterNext();
register_activation_hook( __FILE__, array( 'QSM_Install', 'install' ) );
?>

It would be really nice if the plugin author could include the extra global statement in the next release (or an equivalent alternative fix for WP-CLI issues if this one isn't elegant enough...but it works for me).

**Comment by fpcorso** [comment]
Hey @rklrkl 

I didn't see the previous comment come in with a solution. Sorry about that. I do not use WP-CLI so I hope someone could enlighten me as to how that fixes the issue. 

To be clear, do you just add the global statement here?: https://github.com/fpcorso/quiz_master_next/blob/master/mlw_quizmaster2.php#L289

**Comment by fpcorso** [comment]
Also, thanks @iamdonut for the solution. Sorry for not seeing your comment until now.

**Comment by iamdonut** [comment]
@fpcorso No worries! And yes, that's exactly where it would go. :-)

**Comment by fpcorso** [comment]
I added the global statement in a recent commit which will make its way into 5.1.3 which should be out in the next couple of days. Let me know if anyone experiences this error after the update.
