### ISSUE TITLE
The page you are trying to access is restricted due to a security rule.

### ISSUE THREAD

**Issue by alexandreminem** [fpcorso/quiz_master_next#526]
Hi there!
That's weird, when I add some html code in my questions, i get this warning error.

> The page you are trying to access is restricted due to a security rule.
If you believe the security rule is affecting the normal operation of your website, contact your host support team and provide detailed instructions how to recreate this error. 
They will be able to assist you with rectifying the problem and adjusting the security configuration if needed.

It happens even if I add an url, a picture, some strong text.
I don't get why it happens.
Maybe this has to do with a previous plugin I installed : Secupress. I don't know.

Can you help me with this problem? Thank you very much?

**Comment by fpcorso** [comment]
Hey @alexandreminem.

This is very interesting. I have never seen that warning before. I did a quick search using Google for the warning you received. I saw many similar posts in support forums but didn't see any that were resolved. Have you reached out to your hosting provider and asked them?

**Comment by alexandreminem** [comment]
Huh I don't know how I managed to fix it, but I did!
I think that was something about my files config, with Secupress (it locked some files and stuff).
It's all good right now. :D
