### ISSUE TITLE
Question not evaluated if contains ' & <sub></sub><sup></sub> % ⎷ in the correct answer

### ISSUE THREAD

**Issue by Testbusters** [fpcorso/quiz_master_next#556]
## General description
Escape characters invalid the question if in the right answer

## Expected behavior
It should be possible to insert those characters in every answer: ' & <sub></sub><sup></sub> % ⎷

## Actual behavior
If you use one (or more) of this chars in the right answer it assign 0 points to the question

## Steps to reproduce the behavior
Insert one (or more) of this characters in the correct answer using a point evaluation

**Comment by fpcorso** [comment]
Hey @Testbusters Can you verify if this issue is still occurring in 5.0.6? This update fixed issues with special characters in the answers.

**Comment by Testbusters** [comment]
Hi @fpcorso!
Sorry for the late answer.

The issue seems to be solved in 5.0.6!
Thank you very much! :)
