### ISSUE TITLE
Scheduled timeframe options are not working

### ISSUE THREAD

**Issue by Testbusters** [fpcorso/quiz_master_next#558]
## General description
I set a deadline for my quiz to 25/06/2017, but it still allowed people to compile the quiz until now 19.00 of 26/06/2017.
I first tried to change the deadline to one day before(24/06/2017), but nothing changed, so I had to hide the page of the quiz.
The cache is disabled in every page concerning the quiz.

## Expected behavior
If I set a deadline I expect that the quiz will be closed at the deadline.

## Actual behavior
The quiz is still accessible after the deadline

## Steps to reproduce the behavior
Set a deadline

**Comment by fpcorso** [comment]
Hey @Testbusters 

Thanks for reporting this issue! I will test shortly to see if I can replicate this behavior.

**Comment by fpcorso** [comment]
Was able to replicate this behavior and have pushed a fix to the current developer version. Fix will be in next release.
