### ISSUE TITLE
Max points are wrong if user don't answer to all the questions

### ISSUE THREAD

**Issue by Testbusters** [fpcorso/quiz_master_next#560]
## General description
The maximum achievable points variable %CORRECT_SCORE% displays a wrong value if some questions have not been answered.

## Expected behavior
%CORRECT_SCORE% should display the maximum achievable points

## Actual behavior
If a respondent is leaving some questions (leaving a question is evaluated 0 points) those questions are not considered in the calculation of the maximum achievable points

## Steps to reproduce the behavior
Create a quiz with no obligatory questions and set points for the answers.
Try the quiz, not answering to all the question.
The maximum will be calculated only on the answered ones.

**Comment by fpcorso** [comment]
Hey @Testbusters 

Thank you for choosing to use this plugin!

There is no variable for max points. The %CORRECT_SCORE% variable is the score for the quiz when using correct answers. It shows the score the user earned as the percentage of correct answers out of the total questions. It is not for calculating points.
