### ISSUE TITLE
mlw_qmn_template_variable_results_page filter not working

### ISSUE THREAD

**Issue by johnnya23** [fpcorso/quiz_master_next#571]
## General description
Added this code to functions.php of my child theme:
function jma_survey_var($content, $qmn_quiz_array){
	$content = str_replace('%SURVEY_CHART%', $qmn_quiz_array['email'], $content);
	return  $content ;
}
add_filter( 'mlw_qmn_template_variable_results_page', 'jma_survey_var', 10, 2);

When quiz is submitted ajax wheel just spins indefinitely.

## Expected behavior
Replace '%SURVEY_CHART% with the submitted email addr (or blank) on results page and emails.

## Actual behavior
When quiz is submitted ajax wheel just spins indefinitely.

## Steps to reproduce the behavior
Add this code to functions.php of your child theme:
function jma_survey_var($content, $qmn_quiz_array){
	$content = str_replace('%SURVEY_CHART%', $qmn_quiz_array['email'], $content);
	return  $content ;
}
add_filter( 'mlw_qmn_template_variable_results_page', 'jma_survey_var', 10, 2);

function jma_add_variable_display(){ ?>
    %SURVEY_CHART%
	<?php }
add_action( 'qmn_template_variable_list', 'jma_add_variable_display' );

thx,
john

**Comment by fpcorso** [comment]
Hey @johnnya23 !

Thank you for using this plugin! All of the template variables within the plugin go through that filter, so I do not think it is the filter on its own that is not working. There must be something causing it to not work.

Just to clarify, if you remove the code you supplied, does the quiz submit correctly or does the ajax wheel still spin indefinitely?

**Comment by johnnya23** [comment]
thanks for the response. Have been unable to make the filter work in my
child theme as previously described, but I am able to get it to work in a
plugin. So I'm going that route.
thx,
John

---
John Antonacci
WEB DEVELOPMENT CONSULTANT
CoWEBop Marketing <http://cowebop.com/>
720.549.0023
