### ISSUE TITLE
Missing Global statement in QSM Fields

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#572]
## General description
There is a missing global $wpdb; in the QSM Fields class causing an error when trying to log any errors that are occurring when saving a section.

The error being generated:
Notice: Undefined variable: wpdb in /home/davaarco/training.davaar.com.au/wp-content/plugins/quiz-master-next/php/class-qsm-fields.php on line 64

Notice: Trying to get property of non-object in /home/davaarco/training.davaar.com.au/wp-content/plugins/quiz-master-next/php/class-qsm-fields.php on line 64

**Comment by johnnya23** [comment]
Adding: 
global $wpdb; 
to line 22 of the file in question does not help. Commenting out line 64 does not help.
