### ISSUE TITLE
Tabs pages stop working when translated

### ISSUE THREAD

**Issue by iamleigh** [fpcorso/quiz_master_next#582]
## General description
Tabs not working correctly when pages names are translated causing searches to not show up.

## Expected behavior
Doesn't matter if, for example, "Results" page has been translated to "Resultados" (spanish), when clicking on "Resultados" the result should show up immediately.

## Actual behavior
For example, when "Results" page has been translated to "Resultados" (spanish), is necessary to click again on tabs menu to make page content appear. When doing a results search nothing shows up and is necessary, again, to click on tabs menu to make something appear but when doing this results search empties. Another way to make it work is directly edit URL after search and replace 
`&tab=results` for `&tab=resultados`.

## Steps to reproduce the behavior
1.- Install plugin
2.- Change WP language to "spanish" (or another non-english language)
3.- Make sure on PO file that pages names are translated. For example, "Results" should be "Resultados" in spanish.
4.- Go to the translated page, for example "resultados"
5.- Do a search of results

You will notice content won't show up unless you change in the URL `&tab={original_page_name}` for `&tab={translated_page_name`}.

**Comment by fpcorso** [comment]
Hmmm.... we have many users using a different language. I am surprised that no one else has reported this. Does this happen on all tabs or just the Results tab @iamleigh ?

**Comment by iamleigh** [comment]
I noticed it happens for all tabs.

**Comment by fpcorso** [comment]
This is really odd @iamleigh.

The tabs content is called based on which "slug" is in the URL: https://github.com/fpcorso/quiz_master_next/blob/master/php/quiz-options-page.php#L79

The "slug" is created based on the title: https://github.com/fpcorso/quiz_master_next/blob/master/php/class-qmn-plugin-helper.php#L600

The title is what is passed after translation. For example, here is where the results page tab is registered: https://github.com/fpcorso/quiz_master_next/blob/master/php/options-page-results-page-tab.php#L13

So, if a translation changes the title to something else (like "Results" to "Resultados"), the resulting slug should change as well.

I'm going to have to debug this a bit more with different translations to see if I can figure out what might be going on.

**Comment by vladivanovrf** [comment]
Do you have any news about that? I've faced with the same issue.

**Comment by fpcorso** [comment]
Fixed in #656
