### ISSUE TITLE
I lost all my translation files by accepting an update to version 5.1.2

### ISSUE THREAD

**Issue by faishal20** [fpcorso/quiz_master_next#591]
Hi,

i accepted the update to version 5.1.2 and I lost the translation of the quiz I had done in French. I also checked in the extension folder and the "languages" folder no longer exists.

**Comment by vlood** [comment]
@faishal20 this is what happens with any plugin or theme that you update after you've messed with their files, be it language translations. You'd better use Loco Translate plugin for translations or just keep your translation files in wp-content/languages/plugins/. Also, if you are confident in your translation skills, use the central translation system for the WordPress.org ecosystem here:

https://translate.wordpress.org/locale/fr/default/wp-plugins/quiz-master-next

Once you get your translations approved by a translation editor, and the plugin is at least 95% translated, you'd be having them in your installation AND in your updates.

**Comment by fpcorso** [comment]
Hey @faishal20 

Thanks for using QSM! WordPress 4.6 (April 2016) began the transition from local translation files to the translate.wordpress.org system. Like @vlood mentioned, your best options would be to either use Loco Translate or use the translation system the @vlood linked to above.

Also, thanks @vlood for commenting and helping! I must have missed this issue when it came in.
