### ISSUE TITLE
after completed quize the results not send to admin&quize patisipent

### ISSUE THREAD

**Issue by sudheerkumarnokku** [fpcorso/quiz_master_next#612]
Please provide the following information when creating your issues:

## General description
If this is a bug, give a general description of what you are experiencing. If this is a feature request, include what the feature is that you are requesting.

## Expected behavior
If you are reporting a bug, please describe what you are expecting the plugin to do. If this is a feature request, delete this section.

## Actual behavior
If you are reporting a bug, please describe what you are experiencing. If this is a feature request, delete this section.

## Steps to reproduce the behavior
If you are reporting a bug, describe the exact steps you are taking that results in the behavior described above. If this is a feature request, delete this section.

## Feature request
If you are reporting a bug, delete this section. If you are requesting a feature, please explain what you would like to have in the plugin. Please include examples of other systems/software that may have similar features as well as the exact way you would use this feature.

**Comment by fpcorso** [comment]
Hey @sudheerkumarnokku You did not provide any details in your issue. Please review your issue's comments and fill in the appropriate sections so we can look into any issue that you are encountering.

Remember, this is not a portal to receive support. If you are looking for support, please refer to our "Help" page within the plugin.
