### ISSUE TITLE
Question ordering doesn't work when using older pagination option

### ISSUE THREAD

**Issue by vladivanovrf** [fpcorso/quiz_master_next#657]
Hello

## General description
Seems to be a bug with a question ordering on a page. It's not possible to make a custom question ordering on a page in the latest version of plugin (5.2.3).

## Actual behavior
Right now questions shows on a page in an order they were created

## Steps to reproduce the behavior
1. Create a new quiz  
2. Set "How many questions per page would you like? (Leave 0 for all questions on one page)" to 1 on "Options" tab
2. Create a new page in "Questions" tab
3. Add some questions to the created page
4. Try to change question ordering on the page  

Let me know if you need any help or additional information.
Thanks!

**Comment by fpcorso** [comment]
Hey @vladivanovrf 

There should be a warning that appears on the "Questions" tab when you turn on the "How many questions per page would you like?" option as this is incompatible with the new page/question editor.

When you turn that off, does the order work correctly?

**Comment by vladivanovrf** [comment]
Oh, I'm really sorry, my stupid mistake. Sure, your are absolutely right! Do you have plans to make this option compatible with the new editor?

And just one more question I have: when I tried to delete all pages/questions and press "Save Questions" button, then refresh the page in browser and all removed pages/questions appear again. Looks like it's an issue?
