### ISSUE TITLE
Extra spacing is being added to questions when multiple lines are in question

### ISSUE THREAD

**Issue by sriordan9** [fpcorso/quiz_master_next#659]
## General description
Spacing between lines in the question editor, become either a p-tag or br-tag after leaving question editor.

## Expected behavior
After hitting enter to create space between lines of text, editor should not insert a p-tag or br-tag.

## Actual behavior
While in the question editor, if a space is created by hitting the enter key you can see that it creates a p-tag for the space under the "text" tab. However, when viewing the preview or actual quiz page, the p-tag is replaced with a break tag.

## Steps to reproduce the behavior
Once question is saved (even when space has been created and p-tag manually removed in text tab), if you leave the questions tab then the p-tag or br-tag is inserted (if viewing the editor again or looking at the preview/actual page).

**Comment by vladivanovrf** [comment]
#656 pull request will fix this issue

**Comment by fpcorso** [comment]
Fixed in #656
