### ISSUE TITLE
Bug with HTML in answers

### ISSUE THREAD

**Issue by nmarty195** [fpcorso/quiz_master_next#677]
Hi,

I noticed a weird bug with HTML in answers. It's ok when putting in HTML and it reads it fine, except when we come back to change something in the question or answer, all "<" and ">" are turned to "&...;", and of course if we save the question with this, it won't be showing the HTML anymore.

Any way to fix this?

Thank you!

**Comment by fpcorso** [comment]
Hey @nmarty195 

Thanks for reporting this. Which version of the plugin are you using? Are you using the latest (5.3.1)?

Does this happen on both the "Text" and "Visual" tab for you?

**Comment by nmarty195** [comment]
Thank you. A "Troy A" answered by email to me, too, saying HTML in answer wasn't currently implemented. (Actually, there are no "visual" and "text" tabs for answers, just the fields. It would be great if HTML could stay HTML in these fields! (and even better if it could read shortcodes... but maybe that's asking too much!)

**Comment by fpcorso** [comment]
Ah @nmarty195 Sorry, I missed the "answers" part and thought we were talking about HTML in questions. Yes, the answers **technically** sometimes accepts HTML but it is not a supported feature at the moment as I hope to enhance that capability but couldn't easily do that with technical/legacy features.
