### ISSUE TITLE
Save quiz progress

### ISSUE THREAD

**Issue by sriordan9** [fpcorso/quiz_master_next#697]
## General description
User would like to be able to save quiz progress in addition to simply limiting quiz attempts.

## Feature request
User email: "is there a way that a person can only take a quizz once, and save his progress along the way?"

**Comment by fpcorso** [comment]
@sriordan9 Would this be similar to #250?

**Comment by sriordan9** [comment]
Yes you are correct. I will mention another request has been made, but on issue #250 and close this one.
