### ISSUE TITLE
Timer not working on certain sites when using questions per page option

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#709]
## General description
On some sites, the timer will not activate when moving past the first page on a quiz/survey using the questions per page option.

## Expected behavior
The timer should activate when clicking the "Next" button to move past the first page.

## Actual behavior
The timer never appears or prevents further question answering.

## Steps to reproduce the behavior
1. Create a quiz
2. Set timer to a number besides 0
3. Set questions per page to a number besides 0
4. Ensure there is either text shown before quiz or contact fields
5. Take quiz

**Comment by adrienjolion** [comment]
Hi,
i have the same problem for the progress bar when i use the question per page option.
so i think it's connected

**Comment by fpcorso** [comment]
This issue was resolved in a recent commit to the dev branch.
