### ISSUE TITLE
create new question” “Error:! Please try again.

### ISSUE THREAD

**Issue by yaznet** [fpcorso/quiz_master_next#710]
Hello,

when I click on “create new question”, I encounter the following error: “Error:! Please try again.”

Sorry for my English ;

Site Informations
Site URL: https://seph.yaz.ovh

WordPress Informations
Version: 4.9.7
Language: en_US
Permalink Structure: /%postname%/
Active Theme: Event Star 1.0.2
Parent Theme: Event Star 1.0.2
Debug Mode: Disabled
Memory Limit: 40M

Plugins Informations

Must Use

Active

Acme Demo Setup: 1.0.7
Akismet Anti-Spam: 4.0.8
Contact Form 7: 5.0.3
Hello Dolly: 1.6
Quiz And Survey Master: 6.0.1

Inactive

Server Informations
PHP : 7.0.30
MySQL : 5.6.39
Webserver : Apache

QSM Information
Initial Version : 6.0.1
Current Version : 6.0.1

**Comment by fpcorso** [comment]
Hey @yaznet 

This GitHub repo is not meant for support. Since you already have a ticket in with the same information which we have responded to, I am going to close this issue. Feel free to respond to our response to continue working on resolving this.
