### ISSUE TITLE
pagination system not operational

### ISSUE THREAD

**Issue by adrienjolion** [fpcorso/quiz_master_next#713]
Hi in the quizz system when i set the option 1 question per question , the pagination doesn't appear.
So have you any idea for that (i use the custom CSS and this class : qmn_page_counter_message) ?

**Comment by fpcorso** [comment]
Hey @adrienjolion !

Thank you for trying out QSM. This repo is not meant for support purposes. If you have not done so already, please fill out the form on [our Contact Us page](https://quizandsurveymaster.com/quiz/contact/) so that we can look into this further for you.
