### ISSUE TITLE
Reporting/Analysis addon replaces a question's answer with 2 if user s

### ISSUE THREAD

**Issue by sriordan9** [fpcorso/quiz_master_next#724]
## General description
When a site visitor skips the question this lack of an answer is recorded as an empty string. When there is an empty string, rather than using this in the addon the key for that empty string value is used.

Example: There are two answers to a question, but a user has skipped this question entirely. In the reporting addon, the "answer" (nothing) of the visitor who skipped the question will display as a third question "2"

Example: There are three answers to a question, the last is never chosen, AND one user has skipped that question. The reporting addon will display a third answer "2" instead of the answer that was never chosen.

## Feature request
A check needs to be put in place for users who skip a question. If it happens, the addon should display a message such as "No answer provided"

**Comment by fpcorso** [comment]
@sriordan9 Can you create this issue over in the repo for the addon (repo name: qsm-analysis) so I don't miss it when I update the addon?

**Comment by sriordan9** [comment]
It is now in the addon repo
