### ISSUE TITLE
Allow default email to be deleted or turned off 

### ISSUE THREAD

**Issue by sriordan9** [fpcorso/quiz_master_next#735]
## General description
User would like to be able to prevent all emails from being sent *unless* a user answers all questions of the quiz correctly, in which case they do receive an email.

## Feature request
User email: " I would like to only send email to users who have answered all the questions correctly, but I don't seem to be able to delete the default email template. "

**Comment by fpcorso** [comment]
We can include this with the #379 changes. We probably will not have a default email going forward and let users use that system to create only the emails they need.
