### ISSUE TITLE
6.1 incompatible with wp 4.9.9

### ISSUE THREAD

**Issue by SHoogland** [fpcorso/quiz_master_next#748]
## Site Info
WordPress Version: 4.9.9
QSM Version: 6.1.0
Browser: chrome something, doesn't matter

## General description
I think the following reproduction says enough

## Steps to reproduce the behavior
update to qsm 6.1.0 with wp 4.9 you get an error: PHP Fatal error:  Uncaught Error: Call to undefined function register_block_type()

**Comment by SHoogland** [comment]
i fixed it like this:
``` php
if(function_exists('register_block_type')){
	include 'blocks/block.php';
}
```
in the mlw_quizmaster2.php file but i'm not sure that is the best solution

**Comment by fpcorso** [comment]
Ah @SHoogland !

I don't know how I missed 4.9 in my testing but I have been able to replicate this issue. According to the Gutenberg docs, your solution is one of the recommended approaches. I am implementing that solution now. Thanks!
