### ISSUE TITLE
Add total questions and total pages to Questions tab

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#749]
## General description
Display number of questions and pages on the "Questions" tab.

## Feature request
When creating longer quizzes or tests, it would be useful to be able to know how many questions and pages are in the quiz.

**Comment by inamafridi** [comment]
One of the best plugin but it is not fullfil my requirements...  If I have 500 mcqs and show 10 only at a time after competing these 10 question there should be a pagination(section break) through which i can navigate to even 450 number question.. There is only Next and Previous button..  Another update should be when I click on right answer in multiple chioce it should tik√ correct answer instead  to show me text
