### ISSUE TITLE
Post To Other Social Networks

### ISSUE THREAD

**Issue by fpcorso** [fpcorso/quiz_master_next#94]
Admins would like to be able to post scores to Google+. I need to look into other networks as well to see if they are viable.

**Comment by fpcorso** [comment]
Also, Pinterest as well.

**Comment by OC2PS** [comment]
When looking at Social Networks, the biggest challenge will be preventing clashes with other social plugins. The clashes generally happen when multiple social plugins load the same network's JS. So now many plugins offer the admin the option to load the JS or not. Case in point Social Gallery Lite https://wordpress.org/plugins/social-gallery-lite/
